# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8d1cebf54b3b23678a623f7733152f5268825986eddd8635ca1b494fb02e11f0f8ef8ed1fd6f7fba7769ba0d3e189c76aa0c272b8eb4ef7960c300d56b5a434

test:
  secret_key_base: 0f71e357c4059ff62332c7d83f051844cc46f7d1f171583af9dfda85804f89e67b5c81f2c77333406d1cac0a277e56a8c37034ad89ce8f4568caa14f92798414

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
